### ISSUE TITLE
add custom column to table before adding rows

### ISSUE THREAD

**Issue by lvsltz** [oruebel/ndx-icephys-meta#20]
The same issue as here: https://github.com/NeurodataWithoutBorders/pynwb/issues/1071

This is my workaround. It's copied from the code I shared with you:
```
SweepSeq += 1 
args = {'sweeps': Sweeps,'id': SweepSeq}
# If column added, then the new column is mandatory
if addedNewColSwSeq:
    args['repetition'] = repetition
row_id = nwbfile.add_ic_sweep_sequence(**args)
```

**Comment by oruebel** [comment]
@lvsltz I agree that this will be a very useful feature to add. However, I think this issue is best addressed in HDMF and PyNWB rather than as part of this extension. I'll therefore close this issue here in favor of the existing NeurodataWithoutBorders/pynwb#1071 issue. It may make sense to create an issue on HDMF for this, since this is really an issue with DynamicTable.

**Comment by oruebel** [comment]
Actually, this is not a problem in HDMF. HDMF allows you to add custom columns before a table has been populated. This is actually just an issue with how the SweepsTable is being generated/used. I'll add an example to show how we can do this with the extension soon.

**Comment by oruebel** [comment]
@lvsltz please have a look at Section 3.2.1 in the following notebook https://github.com/oruebel/ndx-icephys-meta/blob/master/src/pynwb/examples/icephys_meta_simple_example.ipynb This shows how you can add custom columns before populating a table with rows. The DynamicTable already supports this, the main issue is that we need to make sure the table actually exists (since it is optional) so we need to make sure the table is being created for us when we need it. The corresponding functions for this already existed as private ``_check`` . I've exposed these functions now as public getter functions so you can get to the tables before populating them with rows via the ``add_...`` functions.
