### ISSUE TITLE
compression of new tables

### ISSUE THREAD

**Issue by lvsltz** [oruebel/ndx-icephys-meta#61]
These tables can potentially be large and repetitive. 
Will there be a way to apply [`H5DataIO`](https://hdmf.readthedocs.io/en/latest/hdmf.backends.hdf5.h5_utils.html#hdmf.backends.hdf5.h5_utils.H5DataIO) on them for compression?

Enrico reports some significant differences in size between a) a NWB file in which each `acquisition` and `stimulation` datasets have been wrapped for compression with `H5DataIO` and b) a NWB file simply archived with gzip.

**Comment by oruebel** [comment]
How big are the differences you are? As a baseline we should see what the overhead is when compressing every dataset in HDF5 vs zipping up the file. I would expect that there is some overhead since in HDF5 datasets are compressed independently vs. zipping up all data at once.

**Comment by EnricoScanta** [comment]
compressing timeseries with :
    H5DataIO(data = data, compression = 'gzip', chunks = True)
compressed.nwb: 5.4 MB
versus:
uncompressed.nwb.gzip: 3 MB
(original uncompressed.nwb: 29 MB)

**Comment by oruebel** [comment]
@EnricoScanta is this for a single TimeSeries and what is the shape and chunk-size of the data? 

I think overall this difference in file size seems reasonable. Some probable  source for the difference are that: 
1) HDF5 compresses the data in blocks, which allows for selective data read/write even if the data is compressed, whereas gzip compresses the data all-at-once, 
2) when wrapping only TimeSeries.data other arrays are not being compressed, 
3) the HDF5 header/footer is not being compressed when wrapping individual datasets,
4) HDF5 and gzip may use different aggression parameters

To test for these different items you could: for: 

1) , 2. set the chunk size in H5DataIO to the full shape of your TimeSeries. I don't recommend to do this in practice as it will likely degrade your read (and write) performance, but it should tell you how much of an influence the chunking has on the compression rate as well as how much is due to other uncompressed data fields.
2) , 3. Rather than specify compression for each dataset, we could add an option to specify a default setting for compression on write to force compression of all datasets. 
4) Increase the aggression parameter in H5DataIO to 9. I my experience an agression of 4 or 5 typically gives a good compromise between overhead in read/write times and file size.

If the difference in file-size is a major concern, then you could try a two-factor compression strategy, i.e., enable chunking+compression for the largest arrays in HDF5 and then do gzip for the whole HDF5 file. I would guess that his approach should: a) get you close to the file size you see with gzip, b) reduce the time for compressing/decompressing the file with gzip, c) keep the bulck data compressed at all times, so that the files would remain  relatively small even when unzipped. A word of caution, in my experience, requiring users and analysis pipelines to explicitly unzip files before they can be used can become a surprisingly large burder and pain-point for users.

**Comment by EnricoScanta** [comment]
The file contained many TmeSeries with different sizes.
Changing the aggression parameter didn't affect much.
It would be a major concert without any compression, but using H5DataIO is ok, and we agree that we prefer not to use gzip.
Therefore I think what you said here would be optimal:
"we could add an option to specify a default setting for compression on write to force compression of all datasets."
Thanks

**Comment by oruebel** [comment]
With HDMF 2.0.1 this is now possible https://github.com/hdmf-dev/hdmf/releases
