### ISSUE TITLE
Prevent binding of stimuli, responses and electrodes metadata dictionaries to external variables

### ISSUE THREAD

**Issue by lvsltz** [oruebel/ndx-icephys-meta#63]
If a dictionary is passed to one of the `stimulus_`, `response_`, `electrode_metadata` arguments, the dictionary is changed with some internal tuples after the call to `add_intracellular_recording`:

Example from **icephys_meta_simple_example.ipynb**:
```python
nwbfile.intracellular_recordings.add_column(
    name='voltage_threshold', 
    data=[0.1, 0.12, 0.13], 
    description='Just and example filter on the electrode',
    category='electrodes') # Just added a PR with this line

em = {}
em['voltage_threshold'] = 2
em
# outputs: {'voltage_threshold': 2}

nwbfile.add_intracellular_recording(electrode=electrode,
    stimulus=stimulus, response=response, recording_tag='B', electrode_metadata = em)

em
# outputs:
# {'voltage_threshold': 2,
#  'electrode': elec0 pynwb.icephys.IntracellularElectrode at 0x4538476176
#  Fields:
#    description: a mock intracellular electrode
#    device: Heka ITC-1600 pynwb.device.Device at 0x4538475536}
```

The issue probably comes from [these lines](https://github.com/oruebel/ndx-icephys-meta/blob/master/src/pynwb/ndx_icephys_meta/icephys.py#L677): `x = popargs('x_metadata', kwargs)`.
I am not sure if this is intended but it's surely unexpected.

**Comment by oruebel** [comment]
Thanks for the issue. You are correct, the issue is that in order to be able to use ``add_row`` function of the ``AlignedDynamicTable`` I need to compile all the data into a single dict so I'm adding the electrode, which is passed in as a separate arg, to the corresponding metadata dictionary:

https://github.com/oruebel/ndx-icephys-meta/blob/8735ec1ba3742de6caad6a6822b426c7983714dc/src/pynwb/ndx_icephys_meta/icephys.py#L676-L680

To avoid the unwanted side-effect you mentioned, the line ``electrodes = popargs('electrode_metadata', kwargs)`` should change to ``electrodes = copy(popargs('electrode_metadata', kwargs))``. I.e., the following lines should all be updated accordingly:

https://github.com/oruebel/ndx-icephys-meta/blob/8735ec1ba3742de6caad6a6822b426c7983714dc/src/pynwb/ndx_icephys_meta/icephys.py#L677

https://github.com/oruebel/ndx-icephys-meta/blob/8735ec1ba3742de6caad6a6822b426c7983714dc/src/pynwb/ndx_icephys_meta/icephys.py#L683

https://github.com/oruebel/ndx-icephys-meta/blob/8735ec1ba3742de6caad6a6822b426c7983714dc/src/pynwb/ndx_icephys_meta/icephys.py#L689
